name: Build Check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-backend:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn --frozen-lockfile
      - run: cd packages/backend && yarn lint
      - run: echo "🍏 This job's status is ${{ job.status }}."

  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn --frozen-lockfile && yarn install
      - run: cd packages/backend && yarn build
      - run: echo "🍏 This job's status is ${{ job.status }}."

  build-frontend:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - run: yarn --frozen-lockfile && yarn install
      - run: cd packages/frontend && yarn build
      - run: echo "🍏 This job's status is ${{ job.status }}."
